[package]
name = "rlox"
version = "0.1.0"
edition = "2024"

[dependencies]


[dev-dependencies]
divan = "0.1.21"
tango-bench = "0.7.2"
dhat = "0.3.3"

[profile.release]
# codegen-units = 1
# lto = true

[profile.bench]
debug = true

[[bench]]
name = "tango"
harness = false

[[bench]]
name = "divan"
harness = false

[[bench]]
name = "dhat"
harness = false

[[bench]]
name = "normal"
harness = false
